export type SeoPageConfig = {
	slug: string;
	label: string;
	routePath: string;
	defaultTitle: string;
	defaultDescription: string;
	defaultKeywords: string;
};

const baseKeywords = 'tally services, tally prime, accounting software, gst filing, business automation';

export const SEO_PAGES: SeoPageConfig[] = [
	{
		slug: 'home',
		label: 'Home',
		routePath: '/',
		defaultTitle: 'Tally Services | Certified Tally Partner & Business Solutions',
		defaultDescription: 'Get TallyPrime licenses, renewals, support, cloud hosting, and expert accounting services from Tally Services.',
		defaultKeywords: `${baseKeywords}, home`,
	},
	{
		slug: 'about-team',
		label: 'About Team',
		routePath: '/about/team',
		defaultTitle: 'Our Team | Tally Services',
		defaultDescription: 'Meet the experienced team behind Tally Services and our customer-focused accounting solutions.',
		defaultKeywords: `${baseKeywords}, team`,
	},
	{
		slug: 'about-journey',
		label: 'About Journey',
		routePath: '/about/journey',
		defaultTitle: 'Our Journey | Tally Services',
		defaultDescription: 'Explore the growth journey of Tally Services and our commitment to long-term customer success.',
		defaultKeywords: `${baseKeywords}, company journey`,
	},
	{
		slug: 'about-why-us',
		label: 'About Why Us',
		routePath: '/about/why-us',
		defaultTitle: 'Why Choose Us | Tally Services',
		defaultDescription: 'Discover why businesses choose Tally Services for trusted implementation, support, and expert guidance.',
		defaultKeywords: `${baseKeywords}, why choose us`,
	},
	{
		slug: 'about',
		label: 'About',
		routePath: '/about',
		defaultTitle: 'About Us | Tally Services',
		defaultDescription: 'Learn about Tally Services, our team, and our mission to deliver practical business and accounting solutions.',
		defaultKeywords: `${baseKeywords}, about tally services`,
	},
	{
		slug: 'products-prime-silver',
		label: 'Product Prime Silver',
		routePath: '/products/prime-silver',
		defaultTitle: 'TallyPrime Silver | Tally Services',
		defaultDescription: 'Buy TallyPrime Silver for single-user businesses with expert setup and support from Tally Services.',
		defaultKeywords: `${baseKeywords}, tallyprime silver`,
	},
	{
		slug: 'products-prime-gold',
		label: 'Product Prime Gold',
		routePath: '/products/prime-gold',
		defaultTitle: 'TallyPrime Gold | Tally Services',
		defaultDescription: 'Get TallyPrime Gold for multi-user businesses with deployment guidance from Tally Services.',
		defaultKeywords: `${baseKeywords}, tallyprime gold`,
	},
	{
		slug: 'products-auditor',
		label: 'Product Auditor',
		routePath: '/products/auditor',
		defaultTitle: 'Tally Auditor Edition | Tally Services',
		defaultDescription: 'Use Tally Auditor Edition with tools tailored for auditors and accounting professionals.',
		defaultKeywords: `${baseKeywords}, tally auditor`,
	},
	{
		slug: 'products-server',
		label: 'Product Server',
		routePath: '/products/server',
		defaultTitle: 'Tally Server 9 | Tally Services',
		defaultDescription: 'Improve performance and concurrency with Tally Server 9 for growing organizations.',
		defaultKeywords: `${baseKeywords}, tally server`,
	},
	{
		slug: 'products-shoper-silver',
		label: 'Product Shoper Silver',
		routePath: '/products/shoper-silver',
		defaultTitle: 'Shoper 9 Silver | Tally Services',
		defaultDescription: 'Manage retail billing and inventory with Shoper 9 Silver setup and support from Tally Services.',
		defaultKeywords: `${baseKeywords}, shoper silver`,
	},
	{
		slug: 'products-shoper-gold',
		label: 'Product Shoper Gold',
		routePath: '/products/shoper-gold',
		defaultTitle: 'Shoper 9 Gold | Tally Services',
		defaultDescription: 'Scale your retail operations with Shoper 9 Gold and integrated accounting features.',
		defaultKeywords: `${baseKeywords}, shoper gold`,
	},
	{
		slug: 'products-bookkeeper',
		label: 'Product Bookkeeper',
		routePath: '/products/bookkeeper',
		defaultTitle: 'Tally Bookkeeper | Tally Services',
		defaultDescription: 'Simplify bookkeeping workflows with Tally Bookkeeper and expert implementation support.',
		defaultKeywords: `${baseKeywords}, bookkeeper`,
	},
	{
		slug: 'products-rent',
		label: 'Product Rent',
		routePath: '/products/rent',
		defaultTitle: 'Tally on Rent | Tally Services',
		defaultDescription: 'Get flexible Tally on Rent plans for affordable and quick business setup.',
		defaultKeywords: `${baseKeywords}, tally on rent`,
	},
	{
		slug: 'products-tvu',
		label: 'Product TVU',
		routePath: '/products/tvu',
		defaultTitle: 'Tally Virtual User | Tally Services',
		defaultDescription: 'Enable remote Tally access securely with Tally Virtual User solutions.',
		defaultKeywords: `${baseKeywords}, tally virtual user`,
	},
	{
		slug: 'products-mobile',
		label: 'Product Mobile',
		routePath: '/products/mobile',
		defaultTitle: 'Tally on Mobile | Tally Services',
		defaultDescription: 'Access Tally reports and business updates on mobile with connected solutions.',
		defaultKeywords: `${baseKeywords}, tally mobile`,
	},
	{
		slug: 'products-more',
		label: 'More Products',
		routePath: '/products/more',
		defaultTitle: 'More Products | Tally Services',
		defaultDescription: 'Explore additional Tally and business products from Tally Services.',
		defaultKeywords: `${baseKeywords}, more products`,
	},
	{
		slug: 'services',
		label: 'Services',
		routePath: '/services',
		defaultTitle: 'Services | Tally Services',
		defaultDescription: 'Explore our services including TSS renewals, cloud solutions, training, accounting, and business consultancy.',
		defaultKeywords: `${baseKeywords}, tally services`,
	},
	{
		slug: 'services-tss',
		label: 'Service TSS',
		routePath: '/services/tss',
		defaultTitle: 'TSS Services | Tally Services',
		defaultDescription: 'Renew and manage TSS effectively with expert help from Tally Services.',
		defaultKeywords: `${baseKeywords}, tss service`,
	},
	{
		slug: 'services-cloud',
		label: 'Service Cloud',
		routePath: '/services/cloud',
		defaultTitle: 'Tally Cloud Services | Tally Services',
		defaultDescription: 'Run Tally on cloud securely with backup, uptime, and remote access support.',
		defaultKeywords: `${baseKeywords}, tally cloud`,
	},
	{
		slug: 'services-training',
		label: 'Service Training',
		routePath: '/services/training',
		defaultTitle: 'Tally Training | Tally Services',
		defaultDescription: 'Learn Tally quickly with practical training programs from certified experts.',
		defaultKeywords: `${baseKeywords}, tally training`,
	},
	{
		slug: 'services-capital',
		label: 'Service Capital',
		routePath: '/services/capital',
		defaultTitle: 'Business Capital Support | Tally Services',
		defaultDescription: 'Get assistance for business capital and growth planning through trusted partners.',
		defaultKeywords: `${baseKeywords}, business capital`,
	},
	{
		slug: 'services-insurance',
		label: 'Service Insurance',
		routePath: '/services/insurance',
		defaultTitle: 'Business Insurance | Tally Services',
		defaultDescription: 'Protect your business with suitable insurance support and consultation.',
		defaultKeywords: `${baseKeywords}, business insurance`,
	},
	{
		slug: 'services-loan',
		label: 'Service Loan',
		routePath: '/services/loan',
		defaultTitle: 'Business Loan Support | Tally Services',
		defaultDescription: 'Explore business loan guidance and financial advisory from Tally Services.',
		defaultKeywords: `${baseKeywords}, business loan`,
	},
	{
		slug: 'services-deposit',
		label: 'Service Deposit',
		routePath: '/services/deposit',
		defaultTitle: 'Deposit Services | Tally Services',
		defaultDescription: 'Get support for deposit planning and related business finance services.',
		defaultKeywords: `${baseKeywords}, deposits`,
	},
	{
		slug: 'services-accounting',
		label: 'Service Accounting',
		routePath: '/services/accounting',
		defaultTitle: 'Accounting Services | Tally Services',
		defaultDescription: 'Professional accounting and compliance services for accurate and timely business reporting.',
		defaultKeywords: `${baseKeywords}, accounting services`,
	},
	{
		slug: 'services-consultancy',
		label: 'Service Consultancy',
		routePath: '/services/consultancy',
		defaultTitle: 'Business Consultancy | Tally Services',
		defaultDescription: 'Improve processes and growth with expert consultancy tailored to your business.',
		defaultKeywords: `${baseKeywords}, consultancy`,
	},
	{
		slug: 'services-more',
		label: 'More Services',
		routePath: '/services/more',
		defaultTitle: 'More Services | Tally Services',
		defaultDescription: 'Discover additional business and technology services from Tally Services.',
		defaultKeywords: `${baseKeywords}, more services`,
	},
	{
		slug: 'products',
		label: 'Products',
		routePath: '/products',
		defaultTitle: 'Products | Tally Services',
		defaultDescription: 'Compare and choose Tally products including Prime Silver, Prime Gold, Server, and add-ons for your business.',
		defaultKeywords: `${baseKeywords}, tally products`,
	},
	{
		slug: 'testimonials',
		label: 'Testimonials',
		routePath: '/testimonials',
		defaultTitle: 'Testimonials | Tally Services',
		defaultDescription: 'Read customer testimonials and feedback about Tally Services solutions and support.',
		defaultKeywords: `${baseKeywords}, testimonials`,
	},
	{
		slug: 'inquiry',
		label: 'Inquiry',
		routePath: '/inquiry',
		defaultTitle: 'Send Inquiry | Tally Services',
		defaultDescription: 'Submit your inquiry to get fast assistance for Tally products and services.',
		defaultKeywords: `${baseKeywords}, inquiry`,
	},
	{
		slug: 'contact',
		label: 'Contact',
		routePath: '/contact',
		defaultTitle: 'Contact Us | Tally Services',
		defaultDescription: 'Contact Tally Services for sales, support, implementation, and customized Tally business solutions.',
		defaultKeywords: `${baseKeywords}, contact`,
	},
	{
		slug: 'solutions-ai',
		label: 'Solution AI',
		routePath: '/solutions/ai',
		defaultTitle: 'AI Solutions | Tally Services',
		defaultDescription: 'Explore AI-driven business solutions from Tally Services for smarter decision making.',
		defaultKeywords: `${baseKeywords}, ai solutions`,
	},
	{
		slug: 'solutions-customization',
		label: 'Solution Customization',
		routePath: '/solutions/customization',
		defaultTitle: 'Tally Customization | Tally Services',
		defaultDescription: 'Get customized Tally features and workflows for your unique business needs.',
		defaultKeywords: `${baseKeywords}, tally customization`,
	},
	{
		slug: 'resources',
		label: 'Resources',
		routePath: '/resources',
		defaultTitle: 'Resources | Tally Services',
		defaultDescription: 'Access business resources, guides, and helpful updates from Tally Services for smarter operations.',
		defaultKeywords: `${baseKeywords}, resources`,
	},
	{
		slug: 'careers',
		label: 'Careers',
		routePath: '/careers',
		defaultTitle: 'Careers | Tally Services',
		defaultDescription: 'Join Tally Services and build your career in accounting technology, customer support, and business consulting.',
		defaultKeywords: `${baseKeywords}, careers`,
	},
	{
		slug: 'clients',
		label: 'Clients',
		routePath: '/clients',
		defaultTitle: 'Clients | Tally Services',
		defaultDescription: 'See how clients across industries trust Tally Services for implementation, support, and growth-focused solutions.',
		defaultKeywords: `${baseKeywords}, clients`,
	},
	{
		slug: 'renew-tss',
		label: 'Renew TSS',
		routePath: '/renew-tss',
		defaultTitle: 'Renew TSS | Tally Services',
		defaultDescription: 'Renew your Tally Software Services quickly with expert assistance and uninterrupted business operations.',
		defaultKeywords: `${baseKeywords}, renew tss`,
	},
	{
		slug: 'upgrade',
		label: 'Upgrade',
		routePath: '/upgrade',
		defaultTitle: 'Upgrade Tally | Tally Services',
		defaultDescription: 'Upgrade your Tally solution with guidance from Tally Services for better performance and latest features.',
		defaultKeywords: `${baseKeywords}, upgrade tally`,
	},
	{
		slug: 'online-payment',
		label: 'Online Payment',
		routePath: '/online-payment',
		defaultTitle: 'Online Payment | Tally Services',
		defaultDescription: 'Make secure online payments for licenses, renewals, and services offered by Tally Services.',
		defaultKeywords: `${baseKeywords}, online payment`,
	},
	{
		slug: 'landing-page',
		label: 'Landing Page',
		routePath: '/landing-page',
		defaultTitle: 'Tally Services Landing Page',
		defaultDescription: 'Discover featured products and services from Tally Services with quick actions and targeted solutions.',
		defaultKeywords: `${baseKeywords}, landing page`,
	},
];

export type SeoPage = string;

export const getSeoPageBySlug = (slug: string): SeoPageConfig | undefined =>
	SEO_PAGES.find((page) => page.slug === slug);

export const buildDefaultHeadTags = (page: SeoPageConfig): string => {
	const canonicalUrl = `https://mittalonlineservices.com${page.routePath}`;
	return [
		`<link rel="canonical" href="${canonicalUrl}" />`,
		'<meta name="robots" content="index,follow,max-image-preview:large" />',
		`<meta property="og:title" content="${page.defaultTitle}" />`,
		`<meta property="og:description" content="${page.defaultDescription}" />`,
		`<meta property="og:url" content="${canonicalUrl}" />`,
		'<meta property="og:type" content="website" />',
		`<meta name="twitter:title" content="${page.defaultTitle}" />`,
		`<meta name="twitter:description" content="${page.defaultDescription}" />`,
		'<meta name="twitter:card" content="summary_large_image" />',
	].join('\n');
};
